//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int id { get; set; }
        public int id_post { get; set; }
        public int id_commentarist { get; set; }
        public string comment { get; set; }
    }
}
