//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        public int id { get; set; }
        public int id_author { get; set; }
        public string content { get; set; }
    }
}
