//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDBSQLServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public int CommentaristId { get; set; }
        public string Comment { get; set; }
    }
}
